language: java

jdk:
  - oraclejdk7

script:
  - mvn -q clean
  - mvn -q initialize
  - mvn -q package
#  - mvn -q site

# after_success: mvn versions:set -DnewVersion=1.0.2-SNAPSHOT

env:
  global:
    secure: bQkAdCXe8nFe/btTAjcCRgCg+9QOmO/nUc7GmCjltKinLnx7azFg4vWTeUEvUiSeMw3lAXp0WlVuxSG35ZSUIjnFNgMMcue3YceTIxOikKaFeQL9C/aJLe+EY0DUuK4cHMO1EvV4TJwOUNsk4IZxEYSXhsxHTIIyyWhL2+HtZYo=
